source 'https://rubygems.org'

gem 'rspec'
gem 'rspec-core'
gem 'selenium-webdriver', '~> 2.53', '>= 2.53.4'
gem 'rack', '~> 2.0', '>= 2.0.1'
gem 'rake'
gem 'rest-client'
gem 'nokogiri'
gem 'parallel'
gem 'parallel_tests'